### ISSUE TITLE
[docs] `changeHandler` and `updateUserHandler` 

### ISSUE THREAD

**Issue by raae** [smallbets/userbase#201]
These two behave slightly different. 

`updateHandler` gets items as the argument, while `updateUserHandler` gets an object (with user as the attribute) as the argument. Might be messing up my terms here, but it would therefore be beneficial with an example also on the init documentation page similar to the one for openDatabase:

This exists:
```
changeHandler: function (items) {
    // update your application state with the database items
}
```

This should be added:
```
updateUserHandler: function ({user}) {
    // update your application state with the updated user
}
```

**Comment by j-berman** [comment]
We're planning on adding a larger "advanced" section to the docs to give clearer examples using many of the optional parameters, this one included. Will keep this open until it's there!

**Comment by j-berman** [comment]
[Done](https://userbase.com/docs/sdk/init/)! Thanks for the feedback
