### ISSUE TITLE
You may only specify one of these parameters: customer, customer_email

### ISSUE THREAD

**Issue by notrab** [smallbets/userbase#211]
I canceled a user via the Stripe dashboard, which yields `subscriptionStatus: "canceled"` in the userbase profile.

If I attempt to `purchaseSubscription` it returns the following error:

```
StripeError: You may only specify one of these parameters: customer, customer_email.
```

**Comment by j-berman** [comment]
Fixed in https://github.com/smallbets/userbase/commit/478b9545aefed7b8389a90ea39e7a218ad1bb721!

**Comment by notrab** [comment]
Nice! I was just about to PR the same after linking it locally.
