### ISSUE TITLE
Track file upload progress

### ISSUE THREAD

**Issue by Fubinator** [smallbets/userbase#220]
When uploading large files, it would be useful to be able to track the progress of the upload (especially for progress bars). Maybe the uploadFile function could get a handler which returns the current progress in certain intervals. 

Example API:
```js
const exampleFile = new File(['example'], 'example.txt', { type: 'text/plain' })

userbase.uploadFile({
  databaseName: 'example-database-name',
  itemId: 'example-id',
  file: exampleFile,
  progressHandler: (bytesTransferred) => console.log(bytesTransferred / exampleFile.size) // => would log percentage
}).then(() => {
  // file stored durably
}).catch((e) => console.error(e))
```

**Comment by j-berman** [comment]
Agreed!

Currently the SDK uploads files in chunks of 512 KB. Would be fairly simple to keep a running `bytesTransferred` inside the SDK. After every 512 KB successfully uploads, add to the to `bytesTransferred`, and call the provided handler. Can do this right [here](https://github.com/smallbets/userbase/blob/3a6adb43b7226e61c9847b5e751b18edbd749eb9/src/userbase-js/src/db.js#L1078), by wrapping the `ws.request` in a promise and adding to the total once it resolves successfully.

Also a slight modification:

```
progressHandler: ({ bytesTransferred }) => {} // developer can do whatever they want with bytesTransferred now
```

This gives us greater freedom to add parameters without worrying about parameter ordering in the future.

**Comment by Fubinator** [comment]
Your proposed modifaction makes total sense. I actually started playing around with it. I'm going to try to get a PR ready soon!
