### ISSUE TITLE
Whitelist Domains for Userbase Apps

### ISSUE THREAD

**Issue by jneterer** [smallbets/userbase#228]
# Problem Statement

At this time, any individual can copy the app id from the application code and use that app id. Although the app id can't be used to access user information, someone could still use that app id to create and deploy a web app that uses it.

# Proposal 

Have the ability to list domains the app id can be used on. I don't believe this is a major security concern and needs addressed right now, but I do think it would be good at some point to put in place as another item to check off with regards to better security/best practices.

Thank you Userbase for all the hard work you do! And for this awesome service!

**Comment by j-berman** [comment]
Agreed! This is on the list of to-do's :)

**Comment by jneterer** [comment]
@j-berman Great to hear! Thanks for the update!

**Comment by j-berman** [comment]
Done!

**Comment by jneterer** [comment]
@j-berman Looks like my comment didn't get posted, thanks @j-berman!!
