### ISSUE TITLE
Pagination and data size limits

### ISSUE THREAD

**Issue by Saunved** [smallbets/userbase#230]
I've been playing with Userbase over the last few days and I have a few doubts regarding how large amounts of data is handled.

Suppose a user's database has over 100mb data. As far as I'm aware, the changeHandler  picks up all items available in the database. Does this mean all 100mb will get downloaded on the client side at some point?

If that is the case, it would be nice to have pagination support. It could be a new endpoint called getDatabasePage with parameters "pageSize", "pageNumber" and "databaseName".

openDatabase can have a parameter "doNotFetch" to avoid downloading all that data. 

**A few alternative approaches**
These are some approaches I've thought of that wouldn't require a new endpoint but will need some client side coding to manage.

(1) Pagination by date ranges
A cheeky alternative to this would be to create a new database every week / month per user depending on the amount of data the app is going to generate and to fetch those databases on-demand. Pagination by date ranges essentially.

(2) Pagination by total items
Create a new database for every X items, depending on item size and keep a database counter in the user's profile.

_Please let me know if my understanding of Userbase is wrong or if I'm missing something important._

Thanks!

**Comment by shamblesides** [comment]
A couple of my users actually do have databases in the 10's of MB. I'll ask and see how it's going for them.

**Comment by shamblesides** [comment]
From that user:

"Its way better now, we had [a chat] with over 500 pages and then we did a new one wich is on 223 pages right now. Since we changed and made a new one we dont have much problems anymore, just tiny disconnects sometimes"

Regarding the first one that was having problems:

"... it fails to connect or is still reconnecting after refreshing a few times, that can take a few mins until it works again."

It's possible that this was actually related to an auxiliary service I was using that was unrelated to userbase, though.

**Comment by shamblesides** [comment]
I could probably provide a somewhat-adequate description of how the database compaction step works but @j-berman would probably do a better job.

**Comment by j-berman** [comment]
@Saunved 

>Suppose a user's database has over 100mb data. As far as I'm aware, the changeHandler picks up all items available in the database. Does this mean all 100mb will get downloaded on the client side at some point?

Yep, when you call openDatabase, the client loads all items in that database into memory.

Couple things to keep in mind that can help you work around this:

1. A user can create many databases as they want. So both of your suggestions are possible to do on your end (Pagination by date ranges, or number of items). For example, Database X contains January 2019 - March 2019, Database Y contains April 2019 - June 2019, etc. We’ve had thoughts about implementing a library that can smoothly handle more complex logic like this.

2. The client does not load files into memory when you open a database. You need to call getFile to load a file into memory, and you can load byte ranges at a time if you want. So if larger items can be stored as files instead, this would be useful.

We understand that the above still may not be ideal for apps where individual users need to store lots of data that needs to be filtered/sorted/queried. We built Userbase in this way to optimize for end-to-end encryption and simplicity. We felt the current approach we settled on had the best set of tradeoffs, that it would be simplest, both to end developers, and to us implementing, and that it would be useful enough to satisfy the largest number of use cases for traditional web apps.

We also benchmarked Userbase a while back, and found it took ~0.3 seconds to fetch and decrypt 1000 todos in a database, ~0.8 seconds for 10k todos, and ~6.4 seconds for 100k (2.9 GHz Macbook Pro with 100 mb/s network). This is likely inaccurate in Userbase's current form, but this performance (and faster) is certainly possible with our current framework. We would like to spend more time optimizing in the future for sure.

**Comment by j-berman** [comment]
@shamblesides 

>"... it fails to connect or is still reconnecting after refreshing a few times, that can take a few mins until it works again."

We do still have some kinks to iron out to prevent this! There is more room for improvement on this front for sure.

**Comment by Saunved** [comment]
@shamblesides @j-berman Thanks a lot for the really helpful responses and helping me understand how things work at the moment. The data load times are pretty fast, so that isn't an issue at all. 

I think if necessary, one can implement pagination based on date ranges. It's a good enough solution for me at the moment.

Thanks a lot again!
Feel free to close the issue :)
