### ISSUE TITLE
TypeScript: optional parameters (databaseName & databaseId)

### ISSUE THREAD

**Issue by mhxbe** [smallbets/userbase#232]
Hi,

I've got a question/suggestion about the provided types.
10 functions require at least **databaseName** or **databaseId**
https://github.com/smallbets/userbase/blob/master/src/userbase-js/types/index.d.ts#L123-L145

**The Problem**
They're both optional parameters so TypeScript doesn't complain when none of them are provided.

**Possible solution**
I was thinking about something like this:
```
type databaseNameOrId = ({ databaseId: string } | { databaseName: string });

export interface Userbase {
  insertItem(
    params: databaseNameOrId & { item: any; itemId?: string }
  ): Promise<void>;
}
```

Personally, I think this syntax is acceptable. However, the type-error that TypeScript generates when none of both parameters are provided is somewhat noisy & possibly unclear.

> Argument of type '{ item: string; }' is not assignable to parameter of type '({ databaseId: string; } & { item: any; itemId?: string; }) | ({ databaseName: string; } & { item: any; itemId?: string; })'.
  Type '{ item: string; }' is not assignable to type '{ databaseName: string; } & { item: any; itemId?: string; }'.
    Property 'databaseName' is missing in type '{ item: string; }' but required in type '{ databaseName: string; }'.

I've made an example repository here where you can try it for yourselves: https://github.com/mhxbe/userbase-database-types
I hope there's a better way of typing this, but I'm not sure.

Suggestions/improvements are welcome.

**Comment by j-berman** [comment]
Good idea!

Additional improvement -- since databaseName and databaseId are mutually exclusive (can only include one, not both), thinking about modifying it like this:

```
type databaseNameXorId = ({ databaseId: string, databaseName?: never } | { databaseName: string, databaseId?: never });
```

See: https://stackoverflow.com/a/44425486/11601853

Agreed the type-error isn't very clear, but, still probably better to point out there's an issue to developers pre-compilation, rather than at run-time when the function throws an error that both are missing or can only include one.

**Comment by mhxbe** [comment]
Great, that's even better!
I shall open up a PR this week. (maybe tomorrow)
I'm not sure how to test types here but we'll review this once the PR is open.

**Comment by j-berman** [comment]
Awesome :)

Check out the test file in `/userbase-js/types/test.ts`

If you pull the latest and run `npm run test:types`, all those tests will run

Also, if you have a linter set up in your IDE, it should give the errors a red squiggle underline like this:

![Screen Shot 2020-11-09 at 7 58 24 PM](https://user-images.githubusercontent.com/26468430/98631577-97c9e680-22d2-11eb-88ca-c8597c5f4346.png)
