### ISSUE TITLE
Append-only databases

### ISSUE THREAD

**Issue by akvadrako** [smallbets/userbase#264]
First, userbase looks very cool. I would like to use it to implement a semi-anonymous chat and I think it's missing a required feature.

One way I can think of doing it is with append-only database permissions. You could allow all users to add items, but not delete or modify anything. Perhaps the shared database could just include pointers to user-specific databases.

If I could run a short script to perform the authorization it would be even better.

Does this sound like a useful addition or is the required functionality already there and I'm just missing it?

**Comment by j-berman** [comment]
You can set a `writeAccess` parameter with the flag `onlyCreator` set to true on items (via [insertItem](https://userbase.com/docs/sdk/insert-item/)). This allows only the item creator or database owner to update or delete an item.

Would that work for you?

**Comment by akvadrako** [comment]
That does sound like it'll work; so I can share a database with write permissions and just ensure every insert has the onlyCreator flag. Thanks, I guess I will close this then.
