### ISSUE TITLE
How to read a database with admin API? (Question)

### ISSUE THREAD

**Issue by leoschuler** [smallbets/userbase#325]
is that a way for the admin credential / API to access data from the users' database? 

I could not see an end point to do that.

I believe that, in order to do that, I would have to create a admin user in the database and share the database with that user. on the server side, I would use the userbase-js-node to login with that admin user and access that database.  

Is this the right assumption? or is there a way to access that data just with the Account access token?

**Comment by jneterer** [comment]
Your assumption is mostly correct! Yes, the user would have to share their database with the admin user. However, you don't **_have_** to user `userbase-js-node` to login with the admin user and access that database, you can simply login per usual as the admin and access the user's shared database all in the client.

**Comment by leoschuler** [comment]
thank you! I realize I don't have to use userbase-js-node, I just forgot to mention the specifics of my use case, the users will have a database of "jobs to be executed in the server". and the admin user will be a scheduled job in a nodejs server. that is why I would be using the userbase-js-node to login and read that database

**Comment by j-berman** [comment]
@leoschuler was your question answered satisfactorily?

**Comment by leoschuler** [comment]
> @leoschuler was your question answered satisfactorily?

yes
