### ISSUE TITLE
How to remove a database?

### ISSUE THREAD

**Issue by leoschuler** [smallbets/userbase#327]
I have created a script to remove all the items in the database, but I could not figure out a way to remove the database itself...

also, I am not sure I choose the best option to remove all the items in the database because I could only get the list of items thru the changeHandler event since opening the database would not return all the items. could you please let me know if this is the best approach to delete all items from a database?

```
    async function deleteDatabase(databaseName) {
        const {databases} = await userbase.getDatabases({databaseName})
        return new Promise( (resolve, reject ) => {
            try { 
                console.log( databases );
                const myDb = databases.filter( db => db.isOwner ).find( db => db.databaseName == databaseName );
                
                if(myDb) {
                userbase.openDatabase( {
                        databaseName : myDb.databaseName,
                        changeHandler: ( dbItems ) => {
                            const ops = dbItems.map( item => ({command:"Delete", itemId:item.itemId }));
                            if( ops.length == 0 ){
                                return resolve(true);
                            }
                            userbase.putTransaction(  { 
                                databaseName : myDb.databaseName, 
                                operations: ops,
                            })
                            .then( () => resolve(true))
                            .catch( e => {console.log(e); reject(e)})
                        }
                    } ).catch( e => {console.log(e); reject(e)})
                    
                } else { 
                    return resolve(true);
                }
            } catch (e) {
                reject(e);
            }
        
        })
    }
```

**Comment by leoschuler** [comment]
ops, I realized now that I could pass the databaseName in the getDatabases method, so I would not need to filter the list of database, but the question regarding deleting the database stills continues

**Comment by BrunoBernardino** [comment]
I can also see this isn't implemented (`userbase.deleteDatabase`) and would like to use it.

**Comment by j-berman** [comment]
Hi! Check out #142, specifically [this comment](https://github.com/smallbets/userbase/issues/142#issuecomment-609102205) for a pointer on how deleting a database can be handled today (by keeping track of deleted databases in a separate database and flagging them to not show to user).

Probably the main problem with deleting items by iterating over all items in this way is you'll hit rate limits for databases with lots of items. If not it'll just take time, and you'll still need to deal with the deleted database at large in some other way.

Looking to add support for an explicit `deleteDatabase` in the next 6-9 months. Going to close this issue in favor of #142.
