### ISSUE TITLE
Automatic Tax Collection with Stripe

### ISSUE THREAD

**Issue by jneterer** [smallbets/userbase#337]
### Problem
I would like to automatically collect tax using Userbase's Stripe Checkout feature but can't because [`userbase-server`](https://github.com/smallbets/userbase/blob/master/src/userbase-server/user.js#L2326) needs to pass an additional property to `checkout.sessions.create({...})`. See ["Collect taxes in Checkout"](https://stripe.com/docs/payments/checkout/taxes?tax-calculation=stripe-tax#new-customers) and ["Automatically collect tax on Checkout sessions"](https://stripe.com/docs/tax/checkout#new-customers). I'm also [validating this with Stripe](https://twitter.com/jacobneterer/status/1486157160497262595?s=20).

### Solution
I'm happy to work on a PR for this!

**Comment by j-berman** [comment]
On implementation (continuing discussion from DM's), I think including `automaticTax` as an optional or advanced parameter in [`purchaseSubscription()`](https://userbase.com/docs/sdk/purchase-subscription/) is the best route. 

Although I'm having a hard time seeing why anyone would want this param to be customizable via the client, if we were to instead go with a toggle in the admin panel's payments portal, I think it adds more clutter to the admin panel UI and makes that more confusing, which is the first thing Userbase devs see. I think tucking it into SDK as an optional (or advanced) parameter is the lesser of the 2 in its capacity to cause confusion/feeling of being overloaded to devs. It also offers more flexibility in case we're not seeing something.

So I vote client-side, and happy to review and test an implementation :)

**Comment by j-berman** [comment]
As discussed in DM, this feature should actually be handled server-side to maintain developer intent. As proposed by me above, if a user does not want their tax automatically calculated and billed, they could theoretically set the param to false in the client, even though the developer may want it to be true.

Thus, I suggest the alternative mentioned above of exposing the feature via a toggle in the Payments Portal of the admin panel. Admins won't see it unless they connect a Stripe account, so it won't clutter the UI for new devs. Plus, I also suggest tucking it into a "Show Advanced" link section of the Payments Portal (see how "+Expand All/-Hide All" work in the app section of the admin panel for a similar kind of UX flow).

Note that this means an admin would choose to collect tax for all plans tied to a single app. If there is demand in the future for a 1-1 mapping of plan to automaticTax boolean value, then it can be added at a future date.

**Comment by j-berman** [comment]
@jneterer how's it workin out? Good to close this?

**Comment by jneterer** [comment]
@j-berman Hey Justin, we can close! My app isn't live yet. Apple denied my submission because I didn't offer in app purchases... So working through that. But this is working in prod!
