### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by vladgolubev** [smallbets/userbase#359]
Hi there. I'm considering using userbase but not sure if this project is still alive. I see no major code changes for 15+ months

<img width="952" alt="CleanShot 2022-04-30 at 21 00 28@2x" src="https://user-images.githubusercontent.com/3817380/166119180-665ee5ee-b88d-4aaa-b9b6-4d111c586beb.png">

I'm afraid that one day it will shut down and delete all the data

**Comment by j-berman** [comment]
Hi there, still alive. It's been humming along with the features on the tin.

The next major feature I intend to work on is a smooth way to export all of your apps' data and import into your own instance of Userbase to alleviate concern on this front. You should be able to click an export button in the admin panel, then we'd email you your apps' data in a file, then you can spin up your own instance of Userbase, create a new admin account, and click an import button in the admin panel passing the file in. Scheduled backups I think would make sense too.

We're still providing support via support@userbase.com in the meantime. I don't believe I'll have time to work on the above feature for the next 3 months -- shooting for August/September.
