### ISSUE TITLE
Service Unavailable for the last couple of days

### ISSUE THREAD

**Issue by BrunoBernardino** [smallbets/userbase#427]
For the last couple of days (and today for many hours), the service has been unavailable ( can't access https://v1.userbase.com, for example, and I can't access apps built with userbase, as well as my paying customers ). There are no replies to emails, nothing on Twitter, what's up? I understand this project is slowly dying, but there are still customers who paid who have customers depending on them. At least a warning stating "we're having some unexpected issues", or "you have x days to export your data" would've been nice.

**Comment by jneterer** [comment]
Same issue here. Paying customers cannot access today. @j-berman @dvassallo any status on what's going on?

**Comment by jneterer** [comment]
Service appears to be back up for the moment... but was definitely down earlier.

**Comment by BrunoBernardino** [comment]
I got an email from @dvassallo stating the root cause had been identified and fixed, so I'm closing this for now, but am definitely prioritizing my migration efforts.
